# Data Preprocessing

## Objectives

- Load the cleaned dataset.
- Identify categorical and numerical features.
- Encode categorical variables.
- Prepare the data for machine learning models.

In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [5]:
df = pd.read_csv("../data/raw/crop_yield.csv")
df.head()

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
0,Arecanut,1997,Whole Year,Assam,73814.0,56708,2051.4,7024878.38,22882.34,0.796087
1,Arhar/Tur,1997,Kharif,Assam,6637.0,4685,2051.4,631643.29,2057.47,0.710435
2,Castor seed,1997,Kharif,Assam,796.0,22,2051.4,75755.32,246.76,0.238333
3,Coconut,1997,Whole Year,Assam,19656.0,126905000,2051.4,1870661.52,6093.36,5238.051739
4,Cotton(lint),1997,Kharif,Assam,1739.0,794,2051.4,165500.63,539.09,0.420909

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19689 entries, 0 to 19688
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Crop             19689 non-null  str
 1   Crop_Year        19689 non-null  int64
 2   Season           19689 non-null  str
 3   State            19689 non-null  str
 4   Area             19689 non-null  float64
 5   Production       19689 non-null  int64
 6   Annual_Rainfall  19689 non-null  float64
 7   Fertilizer       19689 non-null  float64
 8   Pesticide        19689 non-null  float64
 9   Yield            19689 non-null  float64
dtypes: float64(5), int64(2), str(3)
memory usage: 1.5 MB

In [7]:
categorical_cols = df.select_dtypes(include="object").columns
numerical_cols = df.select_dtypes(exclude="object").columns

print("Categorical Columns:")
print(categorical_cols)

print("\nNumerical Columns:")
print(numerical_cols)

Categorical Columns:
Index(['Crop', 'Season', 'State'], dtype='str')

Numerical Columns:
Index(['Crop_Year', 'Area', 'Production', 'Annual_Rainfall', 'Fertilizer',
       'Pesticide', 'Yield'],
      dtype='str')

C:\Users\moham\AppData\Local\Temp\ipykernel_3700\1870020149.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include="object").columns

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19689 entries, 0 to 19688
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Crop             19689 non-null  str
 1   Crop_Year        19689 non-null  int64
 2   Season           19689 non-null  str
 3   State            19689 non-null  str
 4   Area             19689 non-null  float64
 5   Production       19689 non-null  int64
 6   Annual_Rainfall  19689 non-null  float64
 7   Fertilizer       19689 non-null  float64
 8   Pesticide        19689 non-null  float64
 9   Yield            19689 non-null  float64
dtypes: float64(5), int64(2), str(3)
memory usage: 1.5 MB

In [10]:
categorical_cols = df.select_dtypes(include="object").columns
numerical_cols = df.select_dtypes(exclude="object").columns

print("Categorical Columns:")
print(categorical_cols)

print()

print("Numerical Columns:")
print(numerical_cols)

Categorical Columns:
Index(['Crop', 'Season', 'State'], dtype='str')

Numerical Columns:
Index(['Crop_Year', 'Area', 'Production', 'Annual_Rainfall', 'Fertilizer',
       'Pesticide', 'Yield'],
      dtype='str')

C:\Users\moham\AppData\Local\Temp\ipykernel_3700\187688485.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include="object").columns

In [11]:
categorical_cols = df.select_dtypes(include="str").columns
numerical_cols = df.select_dtypes(exclude="str").columns

print("Categorical Columns:")
print(categorical_cols)

print()

print("Numerical Columns:")
print(numerical_cols)

Categorical Columns:
Index(['Crop', 'Season', 'State'], dtype='str')

Numerical Columns:
Index(['Crop_Year', 'Area', 'Production', 'Annual_Rainfall', 'Fertilizer',
       'Pesticide', 'Yield'],
      dtype='str')

label encoding

In [12]:
df.head()

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
0,Arecanut,1997,Whole Year,Assam,73814.0,56708,2051.4,7024878.38,22882.34,0.796087
1,Arhar/Tur,1997,Kharif,Assam,6637.0,4685,2051.4,631643.29,2057.47,0.710435
2,Castor seed,1997,Kharif,Assam,796.0,22,2051.4,75755.32,246.76,0.238333
3,Coconut,1997,Whole Year,Assam,19656.0,126905000,2051.4,1870661.52,6093.36,5238.051739
4,Cotton(lint),1997,Kharif,Assam,1739.0,794,2051.4,165500.63,539.09,0.420909

In [13]:
import pandas as pd

df = pd.read_csv("../data/raw/crop_yield.csv")

In [14]:
df.head()

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
0,Arecanut,1997,Whole Year,Assam,73814.0,56708,2051.4,7024878.38,22882.34,0.796087
1,Arhar/Tur,1997,Kharif,Assam,6637.0,4685,2051.4,631643.29,2057.47,0.710435
2,Castor seed,1997,Kharif,Assam,796.0,22,2051.4,75755.32,246.76,0.238333
3,Coconut,1997,Whole Year,Assam,19656.0,126905000,2051.4,1870661.52,6093.36,5238.051739
4,Cotton(lint),1997,Kharif,Assam,1739.0,794,2051.4,165500.63,539.09,0.420909

In [15]:
from sklearn.preprocessing import LabelEncoder

label_encoders = {}

for col in ["Crop", "Season", "State"]:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

In [16]:
print(label_encoders["Crop"].classes_[:10])

['Arecanut' 'Arhar/Tur' 'Bajra' 'Banana' 'Barley' 'Black pepper'
 'Cardamom' 'Cashewnut' 'Castor seed' 'Coconut ']

In [17]:
import joblib

joblib.dump(label_encoders, "../models/label_encoders.pkl")

print("Label encoders saved successfully!")

Label encoders saved successfully!

In [18]:
X = df.drop("Yield", axis=1)
y = df["Yield"]

print("Features Shape:", X.shape)
print("Target Shape:", y.shape)

Features Shape: (19689, 9)
Target Shape: (19689,)

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (15751, 9)
X_test : (3938, 9)
y_train: (15751,)
y_test : (3938,)

In [20]:
import os

os.makedirs("../data/processed", exist_ok=True)

df.to_csv("../data/processed/crop_yield_processed.csv", index=False)

print("✅ Processed dataset saved successfully!")

✅ Processed dataset saved successfully!

✅ 01_EDA.ipynb
✅ 02_Preprocessing.ipynb
⬜ 03_Model_Training.ipynb
⬜ 04_Model_Evaluation.ipynb
⬜ 05_Gradio_App.ipynb